name: Unsplash Stats

on:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches:
      - master

jobs:
  unsplash_stats_job:
    runs-on: ubuntu-latest
    name: Updates Unsplash stats and blog posts

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Gathering Unsplash stats
      uses: gabrieluizramos/unsplash-stats-workflow@master
      with:
        username: zfett
        ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
        SECRET_KEY: ${{ secrets.UNSPLASH_SECRET_KEY }}
        template: table
