name: Unsplash Stats

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches:
      - master

jobs:
  unsplash_stats_job:
    runs-on: ubuntu-latest
    name: Updates Unsplash stats and blog posts

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Collect and update markdown with Unsplash stats
    - name: Gathering Unsplash stats
      uses: gabrieluizramos/unsplash-stats-workflow@master
      with:
        username: zfett # your unsplash username
        ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
        SECRET_KEY: ${{ secrets.UNSPLASH_SECRET_KEY }}
